export interface ProductState {
  isLoadingProducts: boolean;
  error: boolean;
  errorMessage: string | null;
  products: ProductModel[];
  productToRedeem: ProductModel['_id'] | null;
}

// Generated by https://quicktype.io

export interface ProductModel {
  _id: string;
  name: string;
  cost: number;
  category: string;
  img: Img;
}

export interface Img {
  url: string;
  hdUrl: string;
}

export interface LoadingProductsAction {
  readonly type: 'LOADING';
  payload: {
    isLoadingProducts: boolean;
  };
}

export interface ErrorAction {
  readonly type: 'ERROR';
  payload: {
    isLoading: boolean;
    error: boolean;
    errorMessage: string;
  };
}

export interface ProductsSuccessAction {
  readonly type: 'SUCCESS';
  payload: {
    isLoadingProducts: boolean;
    products: ProductModel[];
    error: boolean;
    errorMessage: null;
  };
}

export type ProductActions =
  | LoadingProductsAction
  | ErrorAction
  | ProductsSuccessAction;
