// Generated by https://quicktype.io

export interface UserModel {
  id: string;
  name: string;
  points: number;
  redeemHistory: any[];
  createDate: string;
}

export interface UserState {
  isLoadingUser: boolean;
  user: UserModel | null;
  error: boolean;
  errorMessage: string | null;
}

export interface LoadingUserAction {
  readonly type: 'LOADING_USER';
  payload: {
    isLoadingUser: boolean;
    error: boolean;
    errorMessage: null;
  };
}

export interface UserSuccessAction {
  readonly type: 'USER_FETCHED';
  payload: {
    isLoadingUser: boolean;
    user: UserModel;
    error: boolean;
    errorMessage: null;
  };
}

export interface UserErrorAction {
  readonly type: 'ERROR_USER';
  payload: {
    isLoadingUser: boolean;
    error: boolean;
    errorMessage: string;
  };
}

export interface AddPointsAction {
  readonly type: 'ADD_POINTS';
  payload: {
    points: number;
  };
}

export interface AddPointsResponse {
  message: string;
  'new Points': number;
}

export type UserActions =
  | LoadingUserAction
  | UserSuccessAction
  | UserErrorAction
  | AddPointsAction;
