//React
import React from 'react';

//Nextjs
import Head from 'next/head';

/**
 * Website meta tags
 */
export const Meta: React.FC = (): JSX.Element => {
  return (
    <Head>
      <title>Aerocommerce</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
  );
};
